# Generated by Django 4.1 on 2022-08-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_user_confirmed_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.user'),
        ),
    ]
