# Generated by Django 4.1 on 2022-08-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_emailconfirmation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8, unique=True)),
                ('day', models.FloatField(default=0)),
                ('week', models.FloatField(default=0)),
                ('month', models.FloatField(default=0)),
                ('users', models.ManyToManyField(to='stocks.user')),
            ],
        ),
    ]
