# Generated by Django 4.1 on 2022-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmation',
            new_name='EmailConfirmations',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='month',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='week',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
